language: r
warnings_are_errors: true
sudo: required
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change
    recipients:
      - kcazelle@uoguelph.ca

r_packages:
  - covr

before_install:
    - echo $SPPPLUS_TOKEN > Renviron
    - chmod 0040 Renviron

after_success:
  - Rscript -e 'covr::codecov()'
